version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./uploads:/app/uploads
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://root:example@mongotfg:27017/organica_db?authSource=admin
      - CORS_ORIGIN=https://organicaproyectofinal-production-ec02.up.railway.appspot
      - JWT-SECRET=your_jwt_secret_here
      - AVATAR_API=https://api.dicebear.com/5.x/initials/svg?seed=
    depends_on:
      - mongotfg
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend 
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=https://organicaproyectofinal-production.up.railway.app
      - VITE_BASE_URL_IMAGE=https://organicaproyectofinal-production.up.railway.app
      - VITE_IDPROJECT=organica-9511b
      - VITE_API_KEY=AIzaSyAbCZiZjgah89GVPjVewbbbFYMb7vopbQc
      - VITE_AUTH_DOMAIN=organica-9511b.firebaseapp.com
      - VITE_STORAGE_BUCKET=organica-9511b.appspot.com
      - VITE_MESSAGING_SENDER_ID=704139277174
      - VITE_APP_ID=1:704139277174:web:86aebf165f5b6736d84057
      - DICEBEAR_API_BASE_URL=https://api.dicebear.com/5.x/initials/svg?seed=
    depends_on:
      - backend
    networks:
      - app-network

  mongotfg:
    image: mongo:latest
    container_name: mongotfg
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongotfg:27017/organica_db?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 123456
    depends_on:
      mongotfg:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: